### ISSUE TITLE
你好 我想请教一下这个插件在QML是如何使用的

### ISSUE THREAD

**Issue by Fourtaketwo** [SindenDev/amap#1]
我按照你的方法成功编译了 库文件 并且添加成功  在QML无法显示地图 如果可以的话， 可以写个例子让我参考下吗？ 谢谢  或者给个联系方式 让我请教下 谢谢

**Comment by angeluslove** [comment]
如果有可能希望可以多写一些关于地图的使用知识，这块一直是空白，非常感谢你的共享

**Comment by SindenDev** [comment]
按照帮助文档的说明的步骤操作。
