### ISSUE TITLE
地图不是高清的

### ISSUE THREAD

**Issue by brucezhao** [SindenDev/amap#2]
首先很感谢作者的工作，我用了你的代码，可以正常显示地图，但是感觉不是高清图，有点粗糙，有没有类似"mapbox.mapping.highdpi_tiles"这样的参数？
再次表示感谢！

**Comment by SindenDev** [comment]
插件调取瓦片接口获取的是png图像，不是矢量图，在缩放时会有些变形模糊；目前也没找到高德的高清图接口，不过也可以考虑加写图像后处理的方法时图像看上去更清晰；

**Comment by brucezhao** [comment]
https://lbs.amap.com/api/webservice/guide/api/staticmaps
这个接口中有个参数scale参数可以设置高清图像，不知道有没有用？

**Comment by SindenDev** [comment]
这个可能用不了，这个接口貌似是地图快照不是地图瓦片。
