### ISSUE TITLE
Geocode 功能无法正常使用

### ISSUE THREAD

**Issue by springer-exe** [SindenDev/amap#3]
```javascript
import QtQuick 2.12
import QtQuick.Window 2.12
import QtPositioning 5.12
import QtLocation 5.12

Window {
    visible: true
    width: 640
    height: 480
    title: qsTr("Hello World")

    Map{
        id: map
        anchors.fill:parent
        plugin: Plugin{
//            name: "osm"
            name: "amap"
        }
    }

    GeocodeModel {
        id: geocodeModel
        plugin: map.plugin
        autoUpdate: true
        query: "吉林长春南湖公园"
        onLocationsChanged: {
            console.log("locations",get(0).address.text)
        }
    }
}
```

测试osm插件正常，amap无返回值

**Comment by SindenDev** [comment]
只针对地图的显示部分做了封装设计，后面Qt Map新扩展的功能如：调整倾斜角、调整视角都是没新加入等；
通过地址查坐标这个可以通过js掉高德的restful api获取

**Comment by springer-exe** [comment]
有没有稍稍详细一点儿的说明或者example啊，想写一个导航类的APP，看到插件很欢喜，但是却不太会用，我看源码里面相当一部分的功能都是完成了的，qml怎么管理高德地图的key啊，好多问题困扰我啊，希望能够得到帮助，万分感谢

**Comment by SindenDev** [comment]
调用高德api的demo
https://github.com/SindenDev/QAMap/blob/master/amap.js
https://github.com/SindenDev/QAMap

看上去你的问题是你对qml中使用Map并不熟悉，你可以运行一下官方的例子， 
Map{
       anchors.fill:parent
	plugin: Plugin{name: "amap" }
}
这样最简单的例子是使用高德amap就犹如使用osm一样
https://github.com/SindenDev/amap/tree/master/example 是一个简单的使用demo，
不用设置key，直接就可以用了
1.将在生成目录编译出插件（以使用MinGW为例子）

	plugins\geoservices\qtgeoservices_amap.dll 
	plugins\geoservices\qtgeoservices_amapd.dll
2.将（qtgeoservices_amap.dll 、qtgeoservices_amapd.dll）拷贝插件到Qt的 plugins\geoservices 定位插件目录

	C:\Qt\Qt5.13.2\5.13.2\mingw53_32\plugins\geoservices
