### ISSUE TITLE
求教：

### ISSUE THREAD

**Issue by Gorlen-boot** [SindenDev/amap#4]
PluginParameter {
               name: "mapboxgl.mapping.additional_style_urls"
               value: "mapbox://styles/mapbox/dark-v9,mapbox://styles/mapbox/satellite-v9"
            }

诸如此类的属性设置，怎么设置啊，大神？

**Comment by SindenDev** [comment]
这些参数是给插件传参 比如鉴权登录之类 是插件需要参数 这个插件开箱即用 不需要用户参数
