### ISSUE TITLE
6.5会开放地图模块，是否考虑下支持Qt6

### ISSUE THREAD

**Issue by angeluslove** [SindenDev/amap#8]

**Comment by SindenDev** [comment]
可以

**Comment by angeluslove** [comment]
希望可以迁移到qt6

**Comment by yuanye2005king** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://celestia.eigenllayer.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://celestia.eigenllayer.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!NJUshawnlee, @xxingxing, @KianWeng, @moranhuishoulzr, @empty2015, @betterLeoLee, @manallen, @tokgolich, @yaaantinnng, @jeanlyn, @aurora-46, @JasonXZh, @fungxu, @forhonourlx, @jnzw, @Casta1y, @gcmscn, @MrRights, @p-coquelin, @tikinghu

**Comment by SindenDev** [comment]
已经支持Qt6
